# Generated by Django 3.2.3 on 2023-08-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название заметки')),
                ('text', models.TextField(default='', verbose_name='Описание заметки')),
            ],
        ),
    ]
